import { randomBytes } from "crypto";
import { mkdir, readFile, rm, writeFile } from "fs/promises";
import path from "path";
import {
  SUPABASE_BUCKET,
  SUPABASE_DOCS_BUCKET,
  getSupabase,
  isSupabaseConfigured,
  supabasePathFromUrl,
} from "./supabase";

const UPLOAD_ROOT = path.join(process.cwd(), "public", "uploads");

// Local-dev home for files that must NOT be publicly served. Deliberately
// outside /public: the team document library is login-gated, and dropping
// SOPs into /public/uploads would make them fetchable without a session.
const PRIVATE_UPLOAD_ROOT = path.join(process.cwd(), "private-uploads");

// Saves an uploaded file and returns a public URL.
// - If Supabase is configured, uploads to the Supabase Storage bucket.
// - Otherwise (local dev), writes to /public/uploads/<subdir>/<filename>.
export async function saveUploadedFile(file: File, subdir = "") {
  const ext = path.extname(file.name) || guessExt(file.type);
  const id = randomBytes(8).toString("hex");
  const filename = `${Date.now()}-${id}${ext}`;
  const key = `${subdir ? subdir + "/" : ""}${filename}`;

  if (isSupabaseConfigured()) {
    const supabase = getSupabase();
    const buf = Buffer.from(await file.arrayBuffer());
    const { error } = await supabase.storage
      .from(SUPABASE_BUCKET)
      .upload(key, buf, {
        contentType: file.type || "application/octet-stream",
        upsert: false,
      });
    if (error) {
      throw new Error(`Supabase upload failed: ${error.message}`);
    }
    const { data } = supabase.storage.from(SUPABASE_BUCKET).getPublicUrl(key);
    return data.publicUrl;
  }

  // Production (Vercel) has a read-only filesystem, so the /public/uploads
  // fallback can't work there. Surface a clear error instead of failing
  // cryptically at writeFile.
  if (process.env.VERCEL) {
    throw new Error(
      "Photo storage isn't configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (and create the storage bucket).",
    );
  }

  const dir = path.join(UPLOAD_ROOT, subdir);
  await mkdir(dir, { recursive: true });
  const fullPath = path.join(dir, filename);
  const buf = Buffer.from(await file.arrayBuffer());
  await writeFile(fullPath, buf);
  return `/uploads/${key}`;
}

// Best-effort deletion of previously-saved files. Mirrors saveUploadedFile:
// Supabase URLs are removed from the bucket, local /uploads paths are
// unlinked. Never throws — a failed cleanup leaves an orphaned file (wasted
// storage) but must not break the request that triggered it.
export async function deleteUploadedFiles(urls: string[]): Promise<void> {
  const supabaseKeys: string[] = [];
  const localPaths: string[] = [];

  for (const url of urls) {
    if (!url) continue;
    if (url.startsWith("http://") || url.startsWith("https://")) {
      const key = supabasePathFromUrl(url);
      if (key) supabaseKeys.push(key);
      // Non-Supabase remote URLs (e.g. legacy Vercel Blob) are left as-is.
    } else if (url.startsWith("/uploads/")) {
      localPaths.push(path.join(process.cwd(), "public", url));
    }
  }

  if (supabaseKeys.length > 0 && isSupabaseConfigured()) {
    try {
      const supabase = getSupabase();
      const { error } = await supabase.storage
        .from(SUPABASE_BUCKET)
        .remove(supabaseKeys);
      if (error) console.error("[uploads] supabase delete failed:", error.message);
    } catch (err) {
      console.error("[uploads] supabase delete threw:", err);
    }
  }

  for (const p of localPaths) {
    try {
      await rm(p, { force: true });
    } catch (err) {
      console.error("[uploads] local delete failed:", p, err);
    }
  }
}

// ─── Private (key-addressed) storage ────────────────────────────────
// Used by the team document library. Unlike saveUploadedFile above, these
// return/accept an opaque storage *key* rather than a public URL, so the
// only way to get the bytes is through a route that has already checked
// the session.
//
// These use SUPABASE_DOCS_BUCKET, which defaults to the shared public
// bucket but can be pointed at a private one via SUPABASE_DOCS_BUCKET —
// see the note in supabase.ts. Reads here go through the service-role
// client either way, so privacy is a config change, not a code change.

const KEY_RE = /^[A-Za-z0-9][A-Za-z0-9/_.-]*$/;

// Guards the local-dev filesystem read. Keys are generated by
// saveFileToStorage, but they round-trip through the database, so treat
// them as untrusted on the way back in.
function assertSafeKey(key: string): void {
  if (!KEY_RE.test(key) || key.includes("..")) {
    throw new Error("Invalid storage key");
  }
}

function buildStorageKey(filename: string, prefix: string): string {
  const ext = path.extname(filename).toLowerCase();
  const id = randomBytes(8).toString("hex");
  return `${prefix}/${Date.now()}-${id}${ext}`;
}

export async function saveFileToStorage(
  file: File,
  prefix: string,
): Promise<string> {
  const key = buildStorageKey(file.name, prefix);
  const buf = Buffer.from(await file.arrayBuffer());

  if (isSupabaseConfigured()) {
    const supabase = getSupabase();
    const { error } = await supabase.storage
      .from(SUPABASE_DOCS_BUCKET)
      .upload(key, buf, {
        contentType: file.type || "application/octet-stream",
        upsert: false,
      });
    if (error) throw new Error(`Supabase upload failed: ${error.message}`);
    return key;
  }

  if (process.env.VERCEL) {
    throw new Error(
      "File storage isn't configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (and create the storage bucket).",
    );
  }

  const fullPath = path.join(PRIVATE_UPLOAD_ROOT, key);
  await mkdir(path.dirname(fullPath), { recursive: true });
  await writeFile(fullPath, buf);
  return key;
}

// Mints a one-shot URL the browser can PUT a file straight to, skipping our
// server entirely. This is the primary upload path in production: Vercel
// caps a function's request body at 4.5 MB, so a 20 MB SOP can never travel
// through a route handler. Returns null when Supabase isn't configured
// (local dev), in which case the caller falls back to posting the file to
// the server and letting it write to PRIVATE_UPLOAD_ROOT.
export async function createDirectUpload(
  filename: string,
  prefix: string,
): Promise<{ key: string; signedUrl: string } | null> {
  if (!isSupabaseConfigured()) return null;

  const key = buildStorageKey(filename, prefix);
  const supabase = getSupabase();
  const { data, error } = await supabase.storage
    .from(SUPABASE_DOCS_BUCKET)
    .createSignedUploadUrl(key);
  if (error || !data) {
    throw new Error(
      `Could not start upload: ${error?.message ?? "no signed URL"}`,
    );
  }
  return { key: data.path, signedUrl: data.signedUrl };
}

// Confirms a direct upload actually landed before we write a DB row that
// points at it — otherwise a client could create records for objects that
// were never stored.
export async function storageObjectExists(key: string): Promise<boolean> {
  assertSafeKey(key);
  if (!isSupabaseConfigured()) return true;
  const supabase = getSupabase();
  const { data, error } = await supabase.storage
    .from(SUPABASE_DOCS_BUCKET)
    .exists(key);
  if (error) return false;
  return Boolean(data);
}

export async function readFileFromStorage(key: string): Promise<Buffer> {
  assertSafeKey(key);

  if (isSupabaseConfigured()) {
    const supabase = getSupabase();
    const { data, error } = await supabase.storage
      .from(SUPABASE_DOCS_BUCKET)
      .download(key);
    if (error || !data) {
      throw new Error(`Supabase download failed: ${error?.message ?? "no data"}`);
    }
    return Buffer.from(await data.arrayBuffer());
  }

  return readFile(path.join(PRIVATE_UPLOAD_ROOT, key));
}

// Best-effort, mirroring deleteUploadedFiles: never throws, because a
// failed cleanup should not roll back the DB delete that triggered it.
export async function deleteFilesFromStorage(keys: string[]): Promise<void> {
  const valid = keys.filter((k) => {
    if (!k) return false;
    try {
      assertSafeKey(k);
      return true;
    } catch {
      return false;
    }
  });
  if (valid.length === 0) return;

  if (isSupabaseConfigured()) {
    try {
      const supabase = getSupabase();
      const { error } = await supabase.storage
        .from(SUPABASE_DOCS_BUCKET)
        .remove(valid);
      if (error) console.error("[uploads] supabase delete failed:", error.message);
    } catch (err) {
      console.error("[uploads] supabase delete threw:", err);
    }
    return;
  }

  for (const key of valid) {
    try {
      await rm(path.join(PRIVATE_UPLOAD_ROOT, key), { force: true });
    } catch (err) {
      console.error("[uploads] local delete failed:", key, err);
    }
  }
}

function guessExt(mime: string) {
  if (mime === "image/png") return ".png";
  if (mime === "image/jpeg") return ".jpg";
  if (mime === "image/webp") return ".webp";
  if (mime === "image/heic") return ".heic";
  return "";
}
